config/routes.rb
Rails.application.routes.draw do
  resources :parks, only: [:show] do
    resources :dinosaurs, only: [:new, :create]
  end
  resources :dinosaurs, only: [:destroy] do
    resources :shifts, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attraction.rb
class Attraction < ApplicationRecord
  # attraction.
  has_many :shifts
  has_many :dinosaurs, through: :shifts
  validates :name, presence: true

  def to_label
    name.capitalize
  end
end

app/models/dinosaur.rb
class Dinosaur < ApplicationRecord
  belongs_to :park
  has_many :shifts
  has_many :attractions, through: :shifts
  SPECIES = ['stegasaurus', 'tyrannosaurus', 'brachiosaurus', 'alex']
  validates :name, presence: true
  # validates :image_url, presence: true
  validates :species, inclusion: { in: SPECIES }
  has_one_attached :photo
end

app/models/park.rb
class Park < ApplicationRecord
  # associations
  has_many :dinosaurs # park.dinosaurs
  # validations
  validates :name, presence: true, uniqueness: true
  validates :banner_url, presence: true
end

app/models/shift.rb
class Shift < ApplicationRecord
  belongs_to :dinosaur
  belongs_to :attraction
  validates_uniqueness_of :dinosaur, scope: :attraction
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dinosaurs_controller.rb
class DinosaursController < ApplicationController
  before_action :set_park, only: [:new, :create]

  def new
    @dinosaur = Dinosaur.new
  end

  def create
    @dinosaur = Dinosaur.new(dinosaur_params)
    @dinosaur.park = @park
    if @dinosaur.save
      redirect_to park_path(@park)
    else
      render :new
    end
  end

  def destroy
    @dinosaur = Dinosaur.find(params[:id])
    @dinosaur.destroy
    redirect_to park_path(@dinosaur.park)
  end

  private

  def dinosaur_params
    params.require(:dinosaur).permit(:name, :species, :image_url, :photo)
  end

  def set_park
    @park = Park.find(params[:park_id])
  end
end

app/controllers/parks_controller.rb
class ParksController < ApplicationController
  before_action :set_park, only: [:show]

  # GET /parks/1
  def show
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_park
    @park = Park.find(params[:id])
  end
end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  def new
    @dinosaur = Dinosaur.find(params[:dinosaur_id])
    @shift = Shift.new
    @attractions = Attraction.where.not(id: @dinosaur.attractions)
  end

  def create
    @dinosaur = Dinosaur.find(params[:dinosaur_id])
    @shift = Shift.new(shift_params)
    @shift.dinosaur = @dinosaur
    if @shift.save
      redirect_to park_path(@dinosaur.park)
    else
      @attractions = Attraction.where.not(id: @dinosaur.attractions)
      render :new
    end
  end

  private

  def shift_params
    params.require(:shift).permit(:attraction_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dinosaurs_helper.rb
module DinosaursHelper
  def dinosaur_photo_url(dinosaur)
    dinosaur.photo.attached? ? cl_image_path(dinosaur.photo.key) : dinosaur.image_url
  end
end

app/helpers/parks_helper.rb
module ParksHelper
end

app/helpers/shifts_helper.rb
module ShiftsHelper
end

app/views/dinosaurs/_card.html.erb
<div class="card-category my-1" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= dinosaur_photo_url(dinosaur) %>)">
  <%= dinosaur.name %>
  <%= link_to new_dinosaur_shift_path(dinosaur), class: 'card-add-link' do %>
    <i class="fas fa-plus-square"></i>
  <% end %>
  <%= link_to dinosaur_path(dinosaur), method: :delete, data: { confirm: "Make #{dinosaur.name} extinct?" }, class: 'card-remove-link' do %>
    <i class="fas fa-meteor"></i>
  <% end %>
  <div class="card-tags">
    <% dinosaur.attractions.each do |attraction| %>
      <span><%= attraction.name %></span>
    <% end %>
  </div>
</div>

app/views/dinosaurs/new.html.erb
<div class="container">
  <h1>Add a Dinosaur</h1>
  <%= simple_form_for [@park, @dinosaur] do |f| %>
    <%= f.input :name %>
    <%= f.input :species, collection: Dinosaur::SPECIES, include_blank: false %>
    <%#= f.input :image_url %>
    <%= f.input :photo, as: :file %>
    <%= f.submit class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DinosaurPark</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/parks/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= @park.banner_url %>);">
  <div class="container">
    <h1><%= @park.name %></h1>
    <p>Change your life and play with dinosaurs.</p>
    <%= link_to 'Add Dinosaur', new_park_dinosaur_path(@park), class: 'btn btn-primary' %>
  </div>
</div>
<div class="container">
  <div class="cards my-3">
    <% @park.dinosaurs.each do |dinosaur| %>
      <%= render 'dinosaurs/card', dinosaur: dinosaur %>
    <% end %>
  </div>
</div>

app/views/shifts/new.html.erb
<div class="container mt-3">
  <h1>Add <%= @dinosaur.name.capitalize %> to an attraction</h1>
  <%= simple_form_for [@dinosaur, @shift] do |f| %>
    <%= f.association :attraction, include_blank: false, collection: @attractions, input_html: { class: 'select2' } %>
    <%= f.submit 'Add', class: 'btn btn-primary' %>
  <% end %>
</div>